apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-fixed-percent-springboot
  namespace: default
spec:
  action: pod-failure
  mode: fixed-percent
  duration: '15s'
  value: '80'
  selector:
    labelSelectors:
      'app': 'springboot-starterkit'