apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-one-springboot
  namespace: default
spec:
  action: pod-failure
  mode: one
  duration: '1m'
  selector:
    labelSelectors:
      'app': 'springboot-starterkit'