apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-one-springboot
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      'app': 'springboot-starterkit'