apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-fixed-springboot
  namespace: default
spec:
  action: pod-kill
  mode: fixed
  value: '2'
  selector:
    labelSelectors:
      'app': 'springboot-starterkit'